import { ReactNode } from "react";

export interface Book {
  amazon_in_product_url: string
  title: string
  author: string
  published_date: string | null
  mrp: number | null
  genre: string
  amazon_in_customer_rating: number
  total_reviews: number
  book_cover_image_url: string
  content: string[]
}

const rawData: [string, string, string, string, string?][] = [
  // PART 1: Understanding Love
  ["PART 1: Understanding Love", "Understanding", "What is Love?", "Love is not merely an emotion; it is the fundamental fabric of existence.", "It is the invisible gravity that draws a fragmented world into unity, revealing that we were never truly separate from each other at all."],
  ["PART 1: Understanding Love", "Understanding", "Meaning of Divine Love", "Divine love is love without condition, expectation, or end.", "It is a holy surrender, looking quietly past the masks of the ego and recognizing the eternal spark in another's eyes."],
  ["PART 1: Understanding Love", "Understanding", "Difference Between Love & Attraction", "Attraction pulls the body; love anchors the soul.", "While attraction is the spark that catches the eye, love is the gentle, unyielding flame that warms the heart through the coldest winters."],
  ["PART 1: Understanding Love", "Understanding", "Emotional vs Spiritual Love", "Emotional love rides the waves of feeling, crashing with sorrow and soaring with joy.", "Spiritual love is the ocean beneath the waves—constant, deep, unchanged by the storms on the surface."],
  ["PART 1: Understanding Love", "Understanding", "The Energy of Love", "If you listen closely, love hums. It is an active frequency.", "When two people vibrate at the same resonant frequency, the universe reshapes itself to protect their quiet symmetry."],
  ["PART 1: Understanding Love", "Understanding", "Love as a Universal Language", "Love needs no translation. A hand held in the dark speaks louder than a thousand poems.", "It is the only absolute truth understood by every living creature under the sun."],
  ["PART 1: Understanding Love", "Understanding", "Love Beyond Words", "There is a profound silence where love resides. When words fail to capture the depth of the heart, quietness steps in to hold the sacred weight of what cannot be spoken."],
  ["PART 1: Understanding Love", "Understanding", "Love and the Soul", "The soul seeks an anchor; love is the harbor.", "To love is to intertwine your deepest essence with another, creating a sanctuary where both spirits can rest in eternal peace."],
  ["PART 1: Understanding Love", "Understanding", "Why Humans Seek Love", "We are born into this world separated from the whole. We spend our lives searching for love because it is our memory of home—the place where we are fully known and fully complete."],
  ["PART 1: Understanding Love", "Understanding", "Love vs Attachment", "Attachment clenches its fist, terrified of losing the flower.", "Love leaves the palm open. It gives sunlight, water, and absolute freedom, knowing true connection cannot be bound by force."],
  ["PART 1: Understanding Love", "Understanding", "Pure Love vs Conditional Love", "Conditional love says, 'I will love you if you make me happy.'", "Pure love says, 'I will love you, even when the happiness fades, until the light returns to both of us.'"],
  ["PART 1: Understanding Love", "Understanding", "The Science of Love (feelings & mind)", "Chemicals spark the fire, but they do not build the temple.", "The brain paints the first blush of romance, while the mind painstakingly chooses devotion every morning thereafter."],
  ["PART 1: Understanding Love", "Understanding", "Love in Silence", "The truest conversations happen long after the talking stops.", "It is the sound of two breaths synchronizing in an empty room, the absolute comfort entirely devoid of performance."],
  ["PART 1: Understanding Love", "Understanding", "Love and Time", "Time is a thief, leaving wrinkles and graying hair, yet it bows in the presence of true love.", "For love takes time, bends it, and weaves it into an unbreakable tapestry of memory."],
  ["PART 1: Understanding Love", "Understanding", "Love and Destiny", "We meet exactly when we are supposed to meet.", "Love is not a series of accidents; it is the invisible, golden thread pulling two wandering souls toward an inevitable intersection."],
  ["PART 1: Understanding Love", "Understanding", "Can Love Be Defined?", "To define love is to trap a cloud in a jar.", "It is endless, shape-shifting, appearing as passion in youth, patience in hardship, and profound peace in old age."],
  ["PART 1: Understanding Love", "Understanding", "The Depth of True Love", "True love does not shy away from the shadows.", "It steps into the darkest, most broken places of a human being and softly declares: 'You are beautiful, even here.'"],
  ["PART 1: Understanding Love", "Understanding", "Love as a Feeling vs Choice", "Feelings are the weather; choice is the house you build to weather the storm.", "Loving someone when the skies are gray is the highest form of devotion."],
  ["PART 1: Understanding Love", "Understanding", "Love in Different Cultures", "Different customs, distinct words, but exactly the same heartbeat.", "Humanity's highest achievement across every culture and era is the unwavering desire to care for another."],
  ["PART 1: Understanding Love", "Understanding", "Final Truth of Love", "The final truth: Love is the beginning and the end.", "We enter this world as helpless infants begging for it, and leave it simply wishing to be remembered by it."],

  // PART 2: Origin of Love
  ["PART 2: Origin of Love", "Origin", "When Did Love Begin?", "Before the stars formed, there was light.", "Love began the moment consciousness split into two, immediately longing to return to the infinite embrace of one."],
  ["PART 2: Origin of Love", "Origin", "Is Love Created or Eternal?", "Love is neither built nor destroyed.", "It is the ancient rhythm of the cosmos; we do not invent it, we merely tune ourselves to its eternal frequency."],
  ["PART 2: Origin of Love", "Origin", "Radha–Krishna: Eternal Love Story", "Radha is the soul, Krishna is the divine.", "Their story is not of possession, but of absolute, consuming devotion—the perfect mirror of a soul yearning for God."],
  ["PART 2: Origin of Love", "Origin", "Love in Mythology", "Gods fought wars for it, and mortals defied death for it.", "Across all myths, love remains the single most powerful force capable of rewriting the laws of the universe."],
  ["PART 2: Origin of Love", "Origin", "Love and Creation of Universe", "The universe was not born of cold mechanics.", "It was a burst of creative expansion; the silent, overwhelming desire of the Void to experience itself in the mirror of life."],
  ["PART 2: Origin of Love", "Origin", "Divine Masculine & Feminine", "Strength and surrender, logic and intuition.", "The universe dances perfectly only when these forces unite, locking hands to create a delicate and beautiful balance."],
  ["PART 2: Origin of Love", "Origin", "Why Souls Attract Each Other", "We are magnets scattered across a chaotic timeline.", "Souls attract because they recognize their missing halves, pieces of an ancient puzzle trying to reunite in a crowded room."],
  ["PART 2: Origin of Love", "Origin", "Destiny and Love", "You do not walk blindly toward love.", "Every heartbreak, every delay, and every tear was an orchestrated step on the staircase leading you directly to them."],
  ["PART 2: Origin of Love", "Origin", "First Sight vs Deep Love", "First sight is the lightning strike; deep love is the slow-growing oak.", "One momentarily illuminates the sky, while the other provides shelter for a lifetime."],
  ["PART 2: Origin of Love", "Origin", "The Role of Karma in Love", "We meet again those we have wronged, and those we have cherished.", "Love cleanses the karmic wheel, turning ancient debts into beautiful bonds of selfless service."],
  ["PART 2: Origin of Love", "Origin", "Love Across Lifetimes", "I have loved you in a thousand different shapes.", "Our bodies decay, our names are forgotten, but the profound resonance of your soul is something my heart will recognize forever."],
  ["PART 2: Origin of Love", "Origin", "Soulmate Concept", "A soulmate is not a perfect person who solves your problems.", "It is someone who serves as a pristine mirror, showing you everything you have been hiding from yourself."],
  ["PART 2: Origin of Love", "Origin", "Twin Flame Concept", "Twin flames are the fierce fire that burns away the ego.", "They challenge us, break us open, and violently force the soul to evolve into its most brilliant and authentic state."],
  ["PART 2: Origin of Love", "Origin", "Spiritual Bonding", "Two minds communicating without sound.", "When spirits bond, proximity becomes irrelevant; you can feel their pain from across the ocean and their smile in your sleep."],
  ["PART 2: Origin of Love", "Origin", "Love Beyond Birth & Death", "Death is an illusion that merely changes the form of the soul.", "The connection forged between deeply loving spirits transcends physical decay, existing loudly in the great silence of eternity."],
  ["PART 2: Origin of Love", "Origin", "Love as Divine Plan", "No meeting is a coincidence.", "The divine architect weaves two lives together precisely when both are ready to guide each other home."],
  ["PART 2: Origin of Love", "Origin", "Love and Consciousness", "Love is the highest expression of consciousness.", "To love is to move past the survival instinct of the animal, attaining the spiritual heights of the divine."],
  ["PART 2: Origin of Love", "Origin", "Cosmic Connection", "We are stardust returning to ourselves.", "When you look into their eyes and see the galaxies, you realize that your love story is written in the constellations."],
  ["PART 2: Origin of Love", "Origin", "Love as God’s Expression", "God cannot be touched, seen, or held.", "But when you unconditionally care for another human being, you become the living, breathing manifestation of the Creator’s heart."],
  ["PART 2: Origin of Love", "Origin", "Beginning of Your Love Story", "It begins inside you.", "Before you can embrace another, you must deeply understand that the love you are searching for has been quietly resting within you all along."],

  // PART 3: Falling in Love
  ["PART 3: Falling in Love", "Falling", "First Feeling of Love", "It hits like a sudden sunrise.", "The chaotic noise of the world mutes, and for a breathtaking moment, everything aligns perfectly in the warmth of their presence."],
  ["PART 3: Falling in Love", "Falling", "Signs You Are in Love", "When a simple notification holds the weight of a letter.", "You find pieces of them in your favorite songs, in the scent of rain, and quietly occupying the empty corners of your mind."],
  ["PART 3: Falling in Love", "Falling", "Emotional Changes in Love", "You become beautifully fragile.", "Your emotional spectrum extends infinitely; their joy violently lifts you to the sky, and their tears heavy your chest like stones."],
  ["PART 3: Falling in Love", "Falling", "Physical Reactions of Love", "A racing pulse, flushed cheeks, and a lightness in the lungs.", "The physical body scrambles to translate the immense electrical surge of a soul expanding."],
  ["PART 3: Falling in Love", "Falling", "Thinking About Someone Constantly", "They become the silent background music of your life.", "No matter what task occupies your hands, the undercurrent of your thoughts flows effortlessly back to their smile."],
  ["PART 3: Falling in Love", "Falling", "Missing Someone Without Reason", "An ache that feels oddly like comfort.", "It is the emotional realization that a piece of your spirit has safely settled inside someone else, and you long for reunion."],
  ["PART 3: Falling in Love", "Falling", "Love vs Infatuation", "Infatuation sprints; love walks.", "Infatuation is obsessed with what someone can give you right now. Love is fascinated by who they are slowly becoming."],
  ["PART 3: Falling in Love", "Falling", "Obsession vs Love", "Obsession demands a tight fist. It fears the exit.", "Love opens the door. It knows you cannot keep the wind in a jar, so it chooses to simply enjoy the breeze while it lasts."],
  ["PART 3: Falling in Love", "Falling", "Love and Vulnerability", "Taking off the armor and praying they do not bring a sword.", "Falling in love requires the terrifying bravery of handing over the map to all your hidden, broken pieces."],
  ["PART 3: Falling in Love", "Falling", "Opening Your Heart", "It feels like unlocking a dark room to let the spring air in.", "After years of self-defense, allowing warmth to flood into the cold corridors of your heart is an act of sheer courage."],
  ["PART 3: Falling in Love", "Falling", "Fear of Falling in Love", "We avoid the heights because we remember the fall.", "But remaining on the ground keeps you safe at the devastating cost of never knowing what it feels like to fly."],
  ["PART 3: Falling in Love", "Falling", "Trust in Love", "Trust is the bridge built over a canyon of doubt.", "You walk it slowly, one blind step at a time, trusting that their hands will catch you if the wood gives way under your feet."],
  ["PART 3: Falling in Love", "Falling", "Love and Overthinking", "The mind panics in the presence of peace.", "It attempts to manufacture problems because absolute bliss feels suspicious the first few times you hold it."],
  ["PART 3: Falling in Love", "Falling", "Communication in Love", "Speaking is easy; understanding is a craft.", "True communication is listening entirely to the hurt hidden beneath their anger, and responding to the pain instead of the volume."],
  ["PART 3: Falling in Love", "Falling", "Respect in Love", "Love without respect is a burning building.", "Respect is the foundation that keeps the passion from turning into chaos. It honors boundaries and cherishes differences."],
  ["PART 3: Falling in Love", "Falling", "Boundaries in Love", "To draw a line is to say: 'This is where I end and you begin'.", "Healthy boundaries protect the relationship by ensuring neither soul is drowned by the other's waves."],
  ["PART 3: Falling in Love", "Falling", "Growth Through Love", "Love is a crucible.", "It gently burns away the selfish, stubborn layers of the ego, leaving behind a polished, empathetic spirit."],
  ["PART 3: Falling in Love", "Falling", "When Love Feels Peaceful", "It is no longer butterflies; it is a deep, quiet exhale.", "You sit comfortably in the silence, realizing that safety is often far more romantic than adrenaline."],
  ["PART 3: Falling in Love", "Falling", "When Love Feels Intense", "A torrential rainstorm of pure longing.", "It asks everything of you, rattling your emotional cages and stretching your capacity to feel until you burst."],
  ["PART 3: Falling in Love", "Falling", "Accepting Love", "The hardest battle is believing you are worthy.", "Accepting love means silencing the ancient voices that deemed you unlovable, and bravely stepping into the warmth."],

  // PART 4: How to Love
  ["PART 4: How to Love", "How to Love", "Loving Without Expectations", "True giving expects absolutely nothing in return.", "It is the purest art form: watering a flower simply because it deserves to bloom, not because you wish to wear it."],
  ["PART 4: How to Love", "How to Love", "Giving vs Taking", "The transaction of ego is a calculated trade of favors.", "The economy of love is completely unbalanced, where both parties relentlessly out-give one another, resulting in infinite abundance."],
  ["PART 4: How to Love", "How to Love", "Listening in Love", "Listening is loving in silence.", "It is putting down your phone, suspending your judgments, and providing the holy sanctuary of your full, undivided attention."],
  ["PART 4: How to Love", "How to Love", "Supporting Your Partner", "You become the architecture they rest upon when exhausted.", "Supporting someone is standing fiercely by their side against the gale of the world, offering an unwavering pillar of strength."],
  ["PART 4: How to Love", "How to Love", "Understanding Emotions", "Behind every reaction is an ancient and fragile root.", "Instead of reacting to their anger, you gently unearth the soil to find the fear or sorrow hiding beneath it."],
  ["PART 4: How to Love", "How to Love", "Being Present", "The only place love genuinely exists is the 'now'.", "Anxiety lives in the future, regret lives in the past. To love is to pull someone directly into the beautiful gravity of the present moment."],
  ["PART 4: How to Love", "How to Love", "Love Through Actions", "A thousand 'I love yous' vanish in the wind.", "But making them coffee in the morning when they are tired builds an unshakeable fortress of trust, brick by silent brick."],
  ["PART 4: How to Love", "How to Love", "Love Through Words", "Words hold the raw power of creation and destruction.", "A well-placed sentence, sincere and deeply observant, can mend a spirit fractured by a hundred chaotic days."],
  ["PART 4: How to Love", "How to Love", "Love Languages", "We often give love exactly how we wish to receive it.", "Wisdom is learning to drop your native tongue and speak to their soul in the language it actually understands."],
  ["PART 4: How to Love", "How to Love", "Forgiveness in Love", "Holding a grudge is drinking poison expecting the other to die.", "Forgiveness wipes the slate clean, refusing to allow yesterday's shadow to eclipse today's sunlight."],
  ["PART 4: How to Love", "How to Love", "Patience in Love", "Growth takes a terrifying amount of time.", "Patience is watering a seed for months without seeing the sprout, knowing that the roots are expanding in the dark."],
  ["PART 4: How to Love", "How to Love", "Kindness in Love", "Kindness is the absolute refusal to be cruel when you have the upper hand.", "It is speaking softly when irritated, and choosing grace when justified anger tempts you."],
  ["PART 4: How to Love", "How to Love", "Sacrifice in Love", "It is not a loss of self; it is a redirection of resources.", "To sacrifice for love is to joyfully surrender a piece of your convenience for the massive expansion of their happiness."],
  ["PART 4: How to Love", "How to Love", "Trust Building", "Trust is built in terrifying, micro-moments of vulnerability.", "Every time they hand you a fragile piece of their fear and you protect it, you mortar another indestructible brick into the wall."],
  ["PART 4: How to Love", "How to Love", "Loyalty in Love", "Loyalty is a choice executed in empty rooms.", "It is remaining undeniably faithful to the connection when you are entirely unobserved, making honoring them a core aspect of your integrity."],
  ["PART 4: How to Love", "How to Love", "Respecting Freedom", "Do not grip so tightly that you crush the flower.", "Respecting their freedom gives them the space to breathe, change, and repeatedly choose you every single day of their own free will."],
  ["PART 4: How to Love", "How to Love", "Avoiding Toxic Love", "Poison often tastes sweet at first sip.", "We must bravely walk away from the chaotic highs and lows that exhaust the spirit, and refuse to confuse pain for passion."],
  ["PART 4: How to Love", "How to Love", "Healthy Love Habits", "Consistent, quiet tending to the garden.", "It is the daily check-ins, the deliberate touch, and the ongoing, intentional effort to never take their presence exclusively for granted."],
  ["PART 4: How to Love", "How to Love", "Growing Together", "We change violently over the years.", "Growing together means giving each other the total permission to evolve, and falling in love with the new versions of yourselves repeatedly."],
  ["PART 4: How to Love", "How to Love", "Becoming Love", "Eventually, it ceases to be something you 'do'.", "You become utterly absorbed in the vibration of compassion, walking through the world entirely as an instrument of love's will."],

  // PART 5: Pain & Separation
  ["PART 5: Pain & Separation", "Pain", "Why Love Hurts", "Because joy and pain rely on the exact same depth of heart.", "You cannot expose yourself to the warmest sun without opening yourself completely to the absolute devastation of the coldest winter."],
  ["PART 5: Pain & Separation", "Pain", "Expectations and Pain", "Expectation is the root of all relational suffering.", "We draft scripts for how they should play their roles, and when they deviate, our illusion breaks, resulting in profound disappointment."],
  ["PART 5: Pain & Separation", "Pain", "Heartbreak", "It feels terribly akin to mourning the dead.", "The heavy, leaden shock that someone who was inextricably woven into your daily existence has abruptly become merely a memory."],
  ["PART 5: Pain & Separation", "Pain", "Moving On", "Moving on is not forgetting.", "It is packing their memory into a beautiful box on the shelf, rather than dragging it aggressively through the messy reality of your present."],
  ["PART 5: Pain & Separation", "Pain", "Healing After Love", "Healing is infuriatingly non-linear.", "Some days you climb mountains; other days a fragile song on the radio destroys your defenses and throws you back to the very beginning."],
  ["PART 5: Pain & Separation", "Pain", "Letting Go", "An active unclenching of the soul's grip.", "To let go is to realize that holding onto a rope made of fire burns you more than totally surrendering to the fall."],
  ["PART 5: Pain & Separation", "Pain", "Unrequited Love", "Pouring vast oceans of water into an empty, sealed vessel.", "The tragic beauty of giving your entire essence to someone who physically or emotionally cannot comprehend the depth of your sacrifice."],
  ["PART 5: Pain & Separation", "Pain", "Long Distance Love", "Loving through screens and timezones.", "It forces the connection completely into the realm of the spirit, where you have to hold onto their soul because your hands cannot hold their skin."],
  ["PART 5: Pain & Separation", "Pain", "Missing Someone Deeply", "A phantom limb of the heart.", "You continually reach out in the darkness to softly trace the shoulder that hasn't occupied your bed for over a year."],
  ["PART 5: Pain & Separation", "Pain", "Overcoming Loss", "The void never fully shrinks.", "Instead, you heroically build a larger life around the edges of the crater, letting time cultivate green grass over the heavy ash."],
  ["PART 5: Pain & Separation", "Pain", "Emotional Healing", "It requires the bravery to sit still in the fire.", "You cannot numb it, you cannot rush it. You must feel every terrifying inch of the agony until the flames eventually exhaust their own oxygen."],
  ["PART 5: Pain & Separation", "Pain", "Self-Recovery", "You remember who you were before they arrived.", "You meticulously dust off your old passions, and you finally grant yourself the massive love you relentlessly poured into them."],
  ["PART 5: Pain & Separation", "Pain", "Finding Strength Again", "Strength is not the absence of crying.", "Strength is falling apart completely on the bedroom floor, wiping your tears in morning light, and bravely showing up for a new day anyway."],
  ["PART 5: Pain & Separation", "Pain", "Love After Pain", "It is terrifyingly difficult to tear down the rebuilt walls.", "But love after profound pain is often the truest love of all, because it is given with eyes wide open to the catastrophic risks."],
  ["PART 5: Pain & Separation", "Pain", "Learning From Breakups", "Every ending is a harsh, brutal graduation.", "They teach you exactly what you cannot tolerate, what you desperately need, and where you failed to stand up for yourself."],
  ["PART 5: Pain & Separation", "Pain", "Forgiving Yourself", "We torture ourselves with 'what ifs' and 'if onlys'.", "Forgiving yourself means acknowledging that you loved them the absolutely best way you knew how with the broken tools you had at the time."],
  ["PART 5: Pain & Separation", "Pain", "Accepting Reality", "The battle ends when you drop the sword of denial.", "Accepting reality is looking directly into the void of their absence and whispering the terrifying words: 'It is actually over.'"],
  ["PART 5: Pain & Separation", "Pain", "Inner Peace After Love", "The storm totally exhausts itself.", "A brilliant, quiet morning breaks over the soul, where their name no longer causes your chest to tighten, but merely evokes a gentle nostalgia."],
  ["PART 5: Pain & Separation", "Pain", "Growth Through Pain", "You fracture, but you heal phenomenally stronger into the breaks.", "We expand exclusively through stretching; the pain of heartbreak is simply the uncomfortable stretching of an evolving soul."],
  ["PART 5: Pain & Separation", "Pain", "Love Never Dies", "Energy simply transforms.", "The pure love you generated for them didn't vanish into thin air; it absorbed entirely into the universe, permanently elevating the collective heart."],

  // PART 6: Divine Love
  ["PART 6: Divine Love", "Divine", "Radha–Krishna Love Meaning", "It represents the eternal dance of creation.", "The individual soul (Radha) endlessly longing to violently merge back into the vast, absolute bliss of the Supreme Consciousness (Krishna)."],
  ["PART 6: Divine Love", "Divine", "Bhakti (Devotion)", "Bhakti is illogical to the thinking mind.", "It is the total, ecstatic shedding of the ego, dancing flawlessly in the fire of worship until the worshipper and the worshipped become one."],
  ["PART 6: Divine Love", "Divine", "Love as Worship", "Looking deeply at another human and seeing the absolute Divine.", "When you treat their joy as a prayer and their pain as a holy sacrament, secular love instantly transforms into spiritual elevation."],
  ["PART 6: Divine Love", "Divine", "Spiritual Connection", "Bodies are merely the temporary vessels that brought us together.", "The connection exists entirely independently of form, resonating in a higher dimension completely untouched by time."],
  ["PART 6: Divine Love", "Divine", "Loving God", "God is not an entity sitting on an external throne.", "To wildly love God is to intimately love the breathing universe, observing the stunning divinity existing in every leaf, breath, and heartbeat."],
  ["PART 6: Divine Love", "Divine", "Surrender in Love", "Surrender is the opposite of defeat.", "It is the massive, victorious letting go of the illusion of control, allowing a higher current to carry the relationship beautifully forward."],
  ["PART 6: Divine Love", "Divine", "Ego vs Love", "The ego builds tall walls; love builds long bridges.", "Where the ego insists on remaining 'right' and violently separate, divine love gracefully yields, dissolving the heavy illusion of 'me and you'."],
  ["PART 6: Divine Love", "Divine", "Pure Devotion", "It asks for no transactional receipt.", "Pure devotion pours perfectly empty, offering everything without the corrupting, selfish desire to be rewarded for its own immense generosity."],
  ["PART 6: Divine Love", "Divine", "Love Without Desire", "Desire wants to totally consume the fire; love simply wants to bask in its warmth.", "Reaching a state where their mere existence is joy enough, free from the heavy gravity of wanting."],
  ["PART 6: Divine Love", "Divine", "Sacred Love", "The space between you is a temple.", "When you walk onto that holy ground, you remove the muddy shoes of judgment, fear, and past traumas, offering only pure transparency."],
  ["PART 6: Divine Love", "Divine", "Inner Peace Through Love", "True love does not agitate the spirit; it entirely stills the turbulent waters.", "It provides a vast, quiet foundation of security where the exhausted mind can finally cease running and safely rest."],
  ["PART 6: Divine Love", "Divine", "Divine Union", "Two flames merging perfectly into one massive light.", "It is the total obliteration of boundaries, an ecstatic spiritual climax where separateness is proven to be an absolute illusion."],
  ["PART 6: Divine Love", "Divine", "Love Beyond Physical", "Tying the knot entirely with the soul.", "When illness, aging, and distance ravage the physical manifestation, this intense, unseen cord holds the structure beautifully intact."],
  ["PART 6: Divine Love", "Divine", "Soul Connection", "An immediate, unexplainable, deeply ancient resonance.", "It feels not like discovering a new land, but dramatically reopening the door to a home you completely forgot you possessed."],
  ["PART 6: Divine Love", "Divine", "Meditation and Love", "Love is a deeply active meditation.", "It anchors you violently to the present moment, utilizing the absolute beauty of the beloved as the flawless focal point of your ultimate attention."],
  ["PART 6: Divine Love", "Divine", "Love and Enlightenment", "Enlightenment is the final dropping of fear.", "When you genuinely love everything without attachment, the massive cosmic joke reveals itself, and you instantly step into absolute light."],
  ["PART 6: Divine Love", "Divine", "Radha’s Devotion", "She possessed nothing, yet she essentially owned the Universe.", "By abandoning all societal logic and plunging fearlessly into the absolute bliss of pure surrender, she became the pinnacle of spiritual ache."],
  ["PART 6: Divine Love", "Divine", "Krishna’s Love", "He is flawlessly detached and yet infinitely accessible.", "Playing the mesmerizing flute that violently awakens the sleeping soul, calling it back through the dark woods to its absolute origin."],
  ["PART 6: Divine Love", "Divine", "Symbolism of Their Love", "It is the grand blueprint of the human condition.", "The desperate heartbreak of separation in the material world beautifully juxtaposed with the immense ecstasy of eternal, inevitable reunion in the spiritual realm."],
  ["PART 6: Divine Love", "Divine", "Becoming Divine Love", "You entirely cease being the cup, and fundamentally become the water itself.", "Moving through every interaction on this earth as a direct conduit for radical grace and unshakeable compassion."],

  // PART 7: Love in Life
  ["PART 7: Love in Life", "Life", "Love in Family", "The first, often imperfect, classroom of the heart.", "It teaches us the heavy baseline of unconditional endurance, binding completely different souls together by the unbreakable rhythm of blood."],
  ["PART 7: Love in Life", "Life", "Love in Friendship", "The beautiful, chosen family of the spirit.", "A sanctuary where we are profoundly loved not by obligation, but by the sheer, magnificent joy of our deeply resonant company."],
  ["PART 7: Love in Life", "Life", "Love in Society", "The invisible mortar holding the bricks of civilization intact.", "Compassion for the stranger on the street is the highest, most advanced marker of our violently evolving human consciousness."],
  ["PART 7: Love in Life", "Life", "Love in Career", "Work without love is exhausting, soulless labor.", "When you pour massive, focused love into your unique craft, it ceases to be a job and wonderfully transforms into profound art and active service."],
  ["PART 7: Love in Life", "Life", "Love and Responsibility", "They are absolutely inseparable sisters.", "To deeply love someone is to boldly shoulder the massive responsibility of meticulously caring for their totally exposed, fragile vulnerabilities."],
  ["PART 7: Love in Life", "Life", "Love and Growth", "A stagnant river turns fundamentally toxic.", "Healthy love acts as a swift, terrifying current that constantly rushes two people towards massive self-improvement and radical accountability."],
  ["PART 7: Love in Life", "Life", "Love and Happiness", "Happiness is the stunning byproduct of love freely given.", "If you try to violently extract happiness from someone else, you fail. If you joyfully pour love into them, happiness abundantly overflows."],
  ["PART 7: Love in Life", "Life", "Love and Mental Health", "Love acts as a brilliant, warm lamp in the pitch-dark corridors of a struggling mind.", "Knowing you are fundamentally seen, accepted, and safely anchored can vastly accelerate the brutal journey out of massive depression."],
  ["PART 7: Love in Life", "Life", "Love and Success", "Empty ambition leaves you utterly starving on a mountain of gold.", "True success is defined incredibly simply: returning home to someone whose eyes light up intensely the magnificent moment you walk through the door."],
  ["PART 7: Love in Life", "Life", "Love in Daily Life", "It lives beautifully in the absolutely mundane.", "Love is profoundly washing their dishes when they are exhausted, and actively listening to their spectacularly boring stories with immense fascination."],
  ["PART 7: Love in Life", "Life", "Expressing Love", "It requires immense bravery to constantly say it out loud.", "Never dangerously assume they already know. Speak your brilliant love loudly and constantly, before time abruptly takes the ultimate option away."],
  ["PART 7: Love in Life", "Life", "Receiving Love", "Many easily give it, but violently block its return.", "You must massively heal the internal shame that secretly tells you that you are fundamentally unworthy of the beautiful things offered to you."],
  ["PART 7: Love in Life", "Life", "Balance in Love", "A beautiful seesaw of giving and taking.", "If one continually pours while the other permanently drinks, the well ultimately runs brutally dry. True love requires a constant, beautiful replenishment."],
  ["PART 7: Love in Life", "Life", "Love and Time Management", "We give time exclusively to the things we genuinely value.", "Telling someone you are entirely 'too busy' simply means their profound importance fundamentally ranks far below your endless external distractions."],
  ["PART 7: Love in Life", "Life", "Love and Self-Respect", "Massive tolerance of disrespect is not profound love; it is profound fear.", "You absolutely cannot love someone correctly while simultaneously setting your own beautiful self-respect violently on fire to keep them warm."],
  ["PART 7: Love in Life", "Life", "Love and Confidence", "To be deeply loved equips you with a massive, invisible armor.", "When you know your absolute core is totally secure, you step brilliantly into the terrifying world with explosive, unapologetic confidence."],
  ["PART 7: Love in Life", "Life", "Love and Purpose", "Love fundamentally *is* the purpose.", "All the money, absolute fame, and raw power eventually crumble to utter dust; only the massive impact of the love you fiercely gave remains entirely eternal."],
  ["PART 7: Love in Life", "Life", "Living With Love", "Approaching every terrifying disaster with massive grace.", "When the engine of your life operates fundamentally on love instead of absolute fear, the chaotic universe beautifully aligns itself exactly to support you."],
  ["PART 7: Love in Life", "Life", "Love and Gratitude", "Gratitude is the immensely powerful fuel that keeps massive love burning bright.", "When you stop wildly appreciating them, resentment silently creeps through the small cracks like dark ivy, slowly suffocating the relationship."],
  ["PART 7: Love in Life", "Life", "Love and Positivity", "Love operates securely at an immensely high vibration.", "It magnetically attracts brilliant light, constantly turning massive challenges into powerful stepping stones and brutal tragedies into profound spiritual lessons."],

  // PART 8: Self Love
  ["PART 8: Self Love", "Self", "What is Self Love?", "It is entirely refusing to abandon yourself.", "Particularly when you brutally fail, make terrible mistakes, and fall completely short of the massive, impossible expectations you placed upon your tired shoulders."],
  ["PART 8: Self Love", "Self", "Importance of Self Love", "You absolutely cannot pour incredibly fresh water from an utterly toxic well.", "How you intimately treat yourself beautifully sets the exact standard for how the entire world is ultimately allowed to treat you."],
  ["PART 8: Self Love", "Self", "Accepting Yourself", "Massively integrating the light and the dark.", "It is boldly looking in the mirror, observing the jagged scars and bizarre flaws, and declaring loudly: 'I am entire, whole, and completely enough.'"],
  ["PART 8: Self Love", "Self", "Healing Yourself", "Viciously doing the brutal, exhausting inner work.", "Sitting silently with your terrifying traumas instead of violently running from them, heavily stitching your massive soul back together with immense golden thread."],
  ["PART 8: Self Love", "Self", "Confidence Building", "Radically keeping the incredibly hard promises you aggressively make to yourself.", "Confidence is not believing they will massively like you; it is profoundly knowing you will be entirely fine even if they absolutely do not."],
  ["PART 8: Self Love", "Self", "Self Respect", "Walking beautifully away from tables where immense emotional starvation is silently served.", "It is violently choosing your brilliant peace over engaging in totally chaotic, dramatic wars that drain your massive spiritual battery."],
  ["PART 8: Self Love", "Self", "Setting Boundaries", "A profound act of fierce self-preservation.", "Politely saying an absolute 'no' to the heavy demands of others so you can finally scream an ecstatic 'yes' directly to your wildly exhausted soul."],
  ["PART 8: Self Love", "Self", "Self Care", "It is far more deeply profound than bubble baths.", "It is aggressively paying your bills, severely cutting off incredibly toxic friendships, and totally reparenting the vastly terrified child living silently inside you."],
  ["PART 8: Self Love", "Self", "Loving Your Flaws", "The breathtaking Japanese art of beautifully filling broken cracks with solid gold.", "Your massive imperfections are spectacularly where the brilliant human light powerfully enters and radically exits your remarkable spirit."],
  ["PART 8: Self Love", "Self", "Inner Peace", "Fiercely detaching from massive external validation.", "Arriving absolutely at a stunning stillness where absolutely no passing compliment can massively elevate you, and absolutely no bitter insult can severely destroy you."],
  ["PART 8: Self Love", "Self", "Mental Strength", "Violently overriding the terrifying, loud inner critic.", "When the heavy, chaotic voices brutally scream that you are totally worthless, mental strength gently whispers with absolute finality: 'I respectfully disagree.'"],
  ["PART 8: Self Love", "Self", "Emotional Balance", "Riding the massive, terrifying waves entirely without ultimately drowning.", "Letting extremely heavy sadness radically wash completely over you logically without totally unpacking your bags and deciding to live miserably inside the tragedy."],
  ["PART 8: Self Love", "Self", "Self Growth", "Painfully shedding the incredibly tight, old skin.", "Fiercely acknowledging that the massively comfortable version of you must utterly die so the deeply brilliant, totally ascended version of you can magnificently emerge."],
  ["PART 8: Self Love", "Self", "Becoming Independent", "Creating total massive security heavily from within.", "Understanding deeply that absolutely nobody is physically coming to dramatically save you—you intensely are the sole architect of your own spectacular rescue."],
  ["PART 8: Self Love", "Self", "Loving Your Journey", "Violently rejecting the immensely toxic timeline of society.", "Deeply honoring your spectacularly unique pace, knowing fiercely that a blooming flower cannot be aggressively rushed by aggressively terrorizing its elegant petals."],
  ["PART 8: Self Love", "Self", "Forgiving Yourself", "Radically extending immense mercy to your deeply younger, massively naive self.", "You uniquely operated strictly on wildly limited information at that time; fiercely release the utterly punishing guilt of intense hindsight entirely."],
  ["PART 8: Self Love", "Self", "Positive Mindset", "An aggressive, daily, brutal mental discipline.", "It is absolutely not wildly ignoring the terrifying darkness; it is intensely, fiercely forcing the deeply exhausted mind to continuously hunt for the magnificent light."],
  ["PART 8: Self Love", "Self", "Inner Happiness", "A heavily fortified, completely untouchable fortress entirely generated within.", "It completely relies on absolutely no other volatile human being, unstable circumstance, or radically fluctuating financial situation to deeply thrive."],
  ["PART 8: Self Love", "Self", "Self Worth", "Deeply realizing your massive value is totally completely unshakeable.", "You are vastly more precious than deep gold simply because you violently exist—utterly independent of how massively productive or physically beautiful you are."],
  ["PART 8: Self Love", "Self", "Becoming Complete", "The magnificent end of the completely desperate external search.", "You radically look across the vast, empty room, make absolutely direct eye contact exactly with your own wild reflection, and boldly smile completely."],

  // PART 9: Philosophy of Love
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Truth", "Love completely violently demands the absolute, horrific truth.", "To brutally hide your deep shadows is to utterly deny your lovely partner the vast privilege of fiercely loving the completely entire you."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Reality", "Massively grounding the wild, chaotic romantic fantasy.", "True love beautifully sweeps the messy kitchen floor long after the completely majestic carriage has aggressively turned violently back into a pumpkin."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love vs Illusion", "Infatuation desperately loves the spectacularly beautiful mirage.", "Deep love fiercely loves the terribly cracked, vastly flawed, heavily real foundation dramatically revealed fiercely when the massive, shimmering illusion suddenly breaks."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Time", "Eternity captured magically in one spectacular fraction of a second.", "Time rapidly destroys massive galaxies, but a truly profound love violently defies physics by beautifully expanding perfectly beyond absolutely all dimensional decay."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Death", "The absolutely final, brutal, ultimate massive test.", "Death completely snatches the fragile physical body, but the massive, brilliant gravitational pull of true love entirely transcends the deep, black soil of the grave."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Destiny", "The utterly magnificent illusion of free will heavily colliding.", "We magically choose who to love, incredibly unaware that our deep, wandering souls precisely signed the massive energetic contract perfectly lifetimes spectacularly prior."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love as Energy", "An absolutely vibrating, fundamentally indestructible frequency.", "It uniquely travels magically through completely dense walls and vastly across brutal screaming oceans instantly to deeply comfort a wildly grieving, chaotic mind."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Universe", "The incredibly cosmic glue powerfully locking the stars.", "The universe fundamentally isn't a completely dead, cold, brutal machine—it is a stunningly living, breathing, massive engine utterly powered primarily by magnetic connection."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Karma", "Exquisite justice completely served violently heavily through the beautiful heart.", "We are magnetically aggressively drawn absolutely to perfectly whoever we need to desperately interact with to wildly break our incredibly stubborn cyclic patterns."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Freedom", "A spectacularly beautiful paradox of intense physics.", "The more heavily and unconditionally you absolutely love violently set someone entirely free, the completely closer their vast soul magically magnetically returns directly to you."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Suffering", "Two intensely brutal sides of precisely the exact same coin.", "Suffering is completely the intense, beautiful price we aggressively, openly, willingly agree fiercely to pay heavily for entirely experiencing absolute profound attachment."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Joy", "The utterly magnificent, explosive flowering of the profoundly secure spirit.", "Deep joy famously erupts entirely effortlessly directly from the massively fertile, beautiful soil of a brilliantly quiet, well-tended, ferociously safe relationship."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Balance", "The beautiful Tao brilliantly operating intimately between two beating hearts.", "Too massive an aggressive grip completely chokes it; too wildly loose a massive grip completely loses it. The stunning magic dramatically is immensely holding entirely beautifully center."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Duality", "Day intensely loving the deep, dark night.", "We desperately incredibly require the massive, painful friction of exactly our wild, opposite traits directly fiercely to rapidly accelerate each beautiful other's magnificent holistic totality."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Existence", "We entirely love, incredibly therefore we absolutely fundamentally are.", "To exist completely entirely devoid of wildly engaging in deep love is to simply heavily, desperately survive mechanically absolutely without essentially uniquely massively living."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Consciousness", "The spectacular ultimate, highest beautiful state of the profoundly awake brain.", "Radical ego death magically achieved entirely not magically by wildly isolating completely alone in a cave, spectacularly but violently by heavily submitting vastly to another entirely."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love and Infinity", "A tiny, fragile drop beautifully returning absolutely violently to the massive ocean.", "Looking incredibly directly intensely deeply into spectacularly familiar human eyes completely incredibly and dramatically recognizing the stunning entirely face exactly of God fiercely looking wildly back."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love Beyond Logic", "The brilliantly completely failing, aggressively chaotic mind totally absolutely massively retreating violently.", "Logic furiously vehemently demands completely protective walls and absolute math; love magnificently famously jumps aggressively straight wildly completely off the spectacular high cliff spectacularly entirely simply because heavily the air violently feels incredibly beautiful completely on massive incredibly its face."],
  ["PART 9: Philosophy of Love", "Philosophy", "Love Beyond Limits", "Expanding fiercely entirely absolutely past spectacular immense exhaustion completely.", "Fiercely deeply giving incredibly massively way far past specifically the very deep boundary where your fiercely rational deep brain aggressively screamed you had utterly completely absolutely absolutely fundamentally entirely absolutely none wildly beautifully heavily immensely left absolutely entirely closely strictly exactly uniquely left."],
  ["PART 9: Philosophy of Love", "Philosophy", "Ultimate Truth of Love", "The absolutely final incredibly profound gorgeous deeply brilliant breathtaking entirely complete gorgeous incredibly massive stunningly beautiful secret.", "There remarkably simply deeply fundamentally is amazingly exclusively literally purely completely exclusively incredibly intensely fiercely utterly undeniably absolutely entirely wonderfully nothing remarkably beautifully else incredibly anywhere."],

  // PART 10: Quotes & Reflections
  ["PART 10: Quotes & Reflections", "Quotes", "Love is not found, it is felt.", "A sudden frequency shift in the silence."],
  ["PART 10: Quotes & Reflections", "Quotes", "Where ego ends, love begins.", "The drop dissolving into the ocean."],
  ["PART 10: Quotes & Reflections", "Quotes", "Radha didn’t love Krishna, she lived him.", "Becoming the song itself."],
  ["PART 10: Quotes & Reflections", "Quotes", "To love is to see God.", "Looking past the physical disguise."],
  ["PART 10: Quotes & Reflections", "Quotes", "Hold tightly, but never heavily.", "The butterfly in the open palm."],
  ["PART 10: Quotes & Reflections", "Quotes", "Patience is love's quiet anchor.", "Waiting through the long winter storms."],
  ["PART 10: Quotes & Reflections", "Quotes", "The heart remembers what the mind forgets.", "An ancient, undeniable vibration."],
  ["PART 10: Quotes & Reflections", "Quotes", "True connection needs no translation.", "The silent language of the soul."],
  ["PART 10: Quotes & Reflections", "Quotes", "Healing begins where judgment ends.", "Grace is the ultimate medicine."],
  ["PART 10: Quotes & Reflections", "Quotes", "A spark fades, but a root deepens.", "The enduring power of genuine depth."],
  ["PART 10: Quotes & Reflections", "Quotes", "Loving you is my highest rebellion.", "Defying the gravity of isolation."],
  ["PART 10: Quotes & Reflections", "Quotes", "Tears are the prayers the heart cannot speak.", "Silent waters of absolute devotion."],
  ["PART 10: Quotes & Reflections", "Quotes", "Freedom is the highest expression of care.", "Loving without building a cage."],
  ["PART 10: Quotes & Reflections", "Quotes", "In the mathematics of love, one plus one equals everything.", "The miracle of total unity."],
  ["PART 10: Quotes & Reflections", "Quotes", "I loved you long before I met you.", "The soul's undeniable prophecy fulfilled."],
  ["PART 10: Quotes & Reflections", "Quotes", "Distance tests the altitude of affection.", "Love simply travels over the waves."],
  ["PART 10: Quotes & Reflections", "Quotes", "Self-love is the first romance.", "You cannot give what you lack."],
  ["PART 10: Quotes & Reflections", "Quotes", "We are all walking each other home.", "The shared pilgrimage of humanity."],
  ["PART 10: Quotes & Reflections", "Quotes", "Grace steps in when logic shatters.", "The ultimate safety net."],
  ["PART 10: Quotes & Reflections", "Quotes", "Eternity is simply an unbroken string of 'nows' spent with you.", "The singular, infinite moment."]
];

export const books: Book[] = rawData.map((data, index) => {
  const content = [];
  if (data[3]) content.push(data[3]);
  if (data[4]) content.push(data[4]);
  return {
    amazon_in_product_url: "#",
    title: `${index + 1}. ${data[2]}`,
    author: data[0],
    published_date: "Timeless",
    mrp: null,
    genre: data[1],
    amazon_in_customer_rating: 5.0,
    total_reviews: 1000 + index * 100,
    book_cover_image_url: `/images/part${Math.floor(index / 20) + 1}.png`,
    content,
  };
});

export const genres = [...new Set(books.map((book) => book.genre))];
