export interface Book {
  amazon_in_product_url: string
  title: string
  author: string
  published_date: string | null
  mrp: number | null
  genre: string
  amazon_in_customer_rating: number
  total_reviews: number
  book_cover_image_url: string
}

export const books: Book[] = [
  {
    amazon_in_product_url: "https://www.amazon.in/Sapiens-Humankind-Yuval-Noah-Harari/dp/0099590085",
    title: "Sapiens: THE MULTI-MILLION COPY BESTSELLER",
    author: "Yuval Noah Harari",
    published_date: "11 June 2015",
    mrp: 699,
    genre: "History & Surveys",
    amazon_in_customer_rating: 4.7,
    total_reviews: 124316,
    book_cover_image_url: "https://m.media-amazon.com/images/I/713jIoMO3UL._SY342_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Beginning-Infinity-Explanations-Transform-World/dp/0670022829",
    title: "Now You See It: How the Brain Science of Attention Will Transform the Way We Live, Work, and Learn",
    author: "Cathy N. Davidson",
    published_date: null,
    mrp: 5678,
    genre: "Psychology",
    amazon_in_customer_rating: 4.2,
    total_reviews: 79,
    book_cover_image_url: "https://m.media-amazon.com/images/I/61HZLQiFjJL._SY342_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Fooled-Randomness-Hidden-Markets-Payoffs/dp/0812979672",
    title: "Fooled by Randomness: The Hidden Role",
    author: "Nassim Nicholas Taleb",
    published_date: "3 May 2007",
    mrp: 699,
    genre: "Econometrics & Statistics",
    amazon_in_customer_rating: 4.4,
    total_reviews: 6029,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71RoZkCMk1L._SY522_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Antifragile-Things-Gain-Disorder-Incerto/dp/0812979680",
    title: "Antifragile: Things that Gain from Disorder",
    author: "Nassim Nicholas Taleb",
    published_date: "6 June 2013",
    mrp: 799,
    genre: "Economics",
    amazon_in_customer_rating: 4.5,
    total_reviews: 7694,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81MS6HSVdsL._SY425_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Black-Swan-Impact-Highly-Improbable/dp/1400043155",
    title: "The Black Swan: The Impact of the Highly Improbable",
    author: "Nassim Nicholas Taleb",
    published_date: null,
    mrp: 699,
    genre: "Theory & Philosophy",
    amazon_in_customer_rating: 4.5,
    total_reviews: 7628,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81IebQqqWtL._SY342_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Skin-Game-Hidden-Asymmetries-Daily/dp/0425428927",
    title: "Skin in the Game",
    author: "Nassim Nicholas Taleb",
    published_date: null,
    mrp: 699,
    genre: "Macroeconomics",
    amazon_in_customer_rating: 4.5,
    total_reviews: 6703,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71cIFCAb6LL._SY466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Bed-Procrustes-Philosophical-Practical-Aphorisms/dp/0374534799",
    title: "Hiroshima",
    author: "John Hersey",
    published_date: null,
    mrp: null,
    genre: "United States",
    amazon_in_customer_rating: 4.4,
    total_reviews: 5306,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71lpvfu-brL._SY466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Influence-Psychology-Persuasion-New-Expanded/dp/0063138808",
    title: "Influence: The Psychology of Persuasion",
    author: "Robert B. Cialdini",
    published_date: null,
    mrp: 2900,
    genre: "Analysis & Strategy",
    amazon_in_customer_rating: 4.6,
    total_reviews: 6929,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71SPjJ+UnLL._SY425_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Fabric-Reality-Parallel-Universes-Implications/dp/014027541X",
    title: "The Fabric of Reality: The Science of Parallel Universes",
    author: "David Deutsch",
    published_date: "1 August 1998",
    mrp: 1743,
    genre: "Literary Theory, History & Criticism",
    amazon_in_customer_rating: 4.3,
    total_reviews: 842,
    book_cover_image_url: "https://m.media-amazon.com/images/I/A1i3g2u1yqL._SY425_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Seven-Brief-Lessons-Physics-Rovelli/dp/0141981725",
    title: "Seven Brief Lessons on Physics",
    author: "Carlo Rovelli",
    published_date: "10 August 2016",
    mrp: 550,
    genre: "Astronomy",
    amazon_in_customer_rating: 4.4,
    total_reviews: 13711,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81Iz11keeTL._SY466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Reality-Not-What-Seems-Journey/dp/0735213933",
    title: "Reality Is Not What It Seems: The Journey to Quantum Gravity",
    author: "Carlo Rovelli",
    published_date: "23 January 2018",
    mrp: 1694,
    genre: "Physics",
    amazon_in_customer_rating: 4.6,
    total_reviews: 4568,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81oiDBb9kXL._SY385_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Snow-Crash-Neal-Stephenson/dp/0241953189",
    title: "Snow Crash",
    author: "Neal Stephenson",
    published_date: null,
    mrp: 699,
    genre: "Contemporary",
    amazon_in_customer_rating: 4.3,
    total_reviews: 19169,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81kAwx7s0-L._SY385_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/The-Diamond-Age/dp/B07CNF2YV3",
    title: "The Diamond Age",
    author: "Neal Stephenson",
    published_date: null,
    mrp: 199,
    genre: "Hard Science Fiction",
    amazon_in_customer_rating: 4.3,
    total_reviews: 4801,
    book_cover_image_url: "https://m.media-amazon.com/images/I/8106uqbBtFL._SX342_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Hitchhiker-Guide-Galaxy-Douglas-Adams/dp/1529034523",
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    published_date: null,
    mrp: 599,
    genre: "History & Criticism",
    amazon_in_customer_rating: 4.5,
    total_reviews: 25793,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71Mt00Ge1XL._SY425_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Three-Body-Problem-Trilogy-Remembrance-Earths-ebook/dp/B0BPCKJJM3",
    title: "The Three-Body Problem Trilogy",
    author: "Cixin Liu",
    published_date: "2 November 2017",
    mrp: 1470,
    genre: "Hard Science Fiction",
    amazon_in_customer_rating: 4.6,
    total_reviews: 6775,
    book_cover_image_url: "https://m.media-amazon.com/images/I/61pZxhWWcPL._SY425_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Ficciones-Jorge-Luis-Borges/dp/0802130305",
    title: "Ficciones",
    author: "Jorge Luis Borges",
    published_date: null,
    mrp: 1306,
    genre: "European",
    amazon_in_customer_rating: 4.3,
    total_reviews: 1153,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71o9S16CpTL._SY466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Sovereign-Individual-Mastering-Transition-Information/dp/0684832720",
    title: "The Sovereign Individual",
    author: "James Dale Davidson",
    published_date: null,
    mrp: 1969,
    genre: "Development & Growth",
    amazon_in_customer_rating: 4.5,
    total_reviews: 1797,
    book_cover_image_url: "https://m.media-amazon.com/images/I/811BLWk2tcL._SY385_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Stories-Your-Life-Others-Chiang/dp/1101972122",
    title: "Stories of Your Life and Others",
    author: "Ted Chiang",
    published_date: "14 June 2016",
    mrp: 1584,
    genre: "History & Criticism",
    amazon_in_customer_rating: 4.5,
    total_reviews: 15658,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71ZRRZShcGL._SY466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Exhalation/dp/B07PGJF395",
    title: "Exhalation",
    author: "Ted Chiang",
    published_date: null,
    mrp: 199,
    genre: "Time Travel",
    amazon_in_customer_rating: 4.5,
    total_reviews: 13942,
    book_cover_image_url: "https://m.media-amazon.com/images/I/81AC92ncoEL._SX466_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Book-Life-J-Krishnamurti/dp/0060648791",
    title: "The Book of Life: Daily Meditations",
    author: "J. Krishnamurti",
    published_date: null,
    mrp: 1595,
    genre: "Motivational",
    amazon_in_customer_rating: 4.6,
    total_reviews: 1606,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71IIi-KnvAL._SY342_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Total-Freedom-Essential-Krishnamurti/dp/0060648805",
    title: "Total Freedom",
    author: "J. Krishnamurti",
    published_date: "2 December 1996",
    mrp: 999,
    genre: "Motivational",
    amazon_in_customer_rating: 4.6,
    total_reviews: 389,
    book_cover_image_url: "https://m.media-amazon.com/images/I/71rfJk8zO0L._SY385_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Tao-Te-Ching-Lao-Tzu/dp/014044131X",
    title: "Tao Te Ching",
    author: "Lao Tzu",
    published_date: "26 January 2000",
    mrp: 450,
    genre: "Essays",
    amazon_in_customer_rating: 4.4,
    total_reviews: 1258,
    book_cover_image_url: "https://m.media-amazon.com/images/I/91o4LY9vW-L._SY522_.jpg",
  },
  {
    amazon_in_product_url: "https://www.amazon.in/Letters-Penguin-Classics-Lucius-Annaeus/dp/0140442103",
    title: "Letters From A Stoic",
    author: "Annaeus Lucius Seneca",
    published_date: "26 August 2004",
    mrp: 450,
    genre: "Rome",
    amazon_in_customer_rating: 4.5,
    total_reviews: 5756,
    book_cover_image_url: "https://m.media-amazon.com/images/I/61ahwmdD6-L._SY522_.jpg",
  },
]

export const genres = [...new Set(books.map((book) => book.genre))]
